### ISSUE TITLE
Cannot cancel a single goal

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/my-action-server#2]
If I call 

```bash
rostopic pub /my_action_server/cancel actionlib_msgsoalID "stamp:
  secs: 0
  nsecs: 0
id: ''" 
```

however, if we add an id of a currently active goal it does not work.

Moreover, if you call this more than once an error

```
[ERROR] [1555689970.982826]: Attempt to get a goal id on an uninitialized ServerGoalHandle
```

appears ...

**Comment by TiagoaTavares** [comment]
Im trying to fix it....
I discovered that Cancelcallback only gets activate when id is empty... but i dont know why...

**Comment by miguelriemoliveira** [comment]
Hi @TiagoaTavares 

Got it. There is an internal goal id which is not what we had. Our id was defined in the action and was not the id that we to be given when calling to cancel. Changed our action **id** to **number**.

If we call with the proper goal id it all works fine, take a look:

![Untitled](https://user-images.githubusercontent.com/11350998/56447578-fe5a6e80-6300-11e9-84fa-90224d2f16b6.png)


Updated the readme as well.

**Comment by miguelriemoliveira** [comment]
@TiagoaTavares , please test from your side to see if its working ...
