### ISSUE TITLE
change the name of the ros package to my_action_server

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/my-action-server#3]
Can I ask for your help with this @TiagoaTavares ?

It is a matter of changing the package.xml and the CMakeLists.txt

**Comment by TiagoaTavares** [comment]
Done!

**Comment by miguelriemoliveira** [comment]
you should also change the instructions on the readme ...

**Comment by TiagoaTavares** [comment]
now its done! But i have a problem, when i try to execute it... 
ERROR: "from my_action_server.msg import MyActionAction, MyActionGoal, MyActionFeedback, MyActionResult
ImportError: No module named msg "

**Comment by miguelriemoliveira** [comment]
Did you compile the new action?

**Comment by TiagoaTavares** [comment]
yes... The action files were created on devel...

**Comment by miguelriemoliveira** [comment]
ok, commit and push and I will give it a try from here ...

**Comment by TiagoaTavares** [comment]
i have already commit. it is the last one

**Comment by miguelriemoliveira** [comment]
It is working now. See b1d687b9f8398bca50eab41256fb5da49fbb1fe9

Changed the name of the python script not to collide with the package name. Can with update the readme accordingly please?

**Comment by TiagoaTavares** [comment]
now it's working https://github.com/miguelriemoliveira/my-action-server/commit/006db05e484104c8e5602016377964a05b5167e8 ! :)
