### ISSUE TITLE
Create a test action client

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/my-action-server#4]
Hi @TiagoaTavares ,

can you create one?

**Comment by TiagoaTavares** [comment]
I made a simple one, and it's working :)
I can make a c++ too, if you want...

**Comment by miguelriemoliveira** [comment]
C++? What is that?  :)

A Dom, 21/04/2019, 16:27, Tiago Tavares <notifications@github.com> escreveu:
